## Dockerfile for project development



## Base image
FROM ubuntu:20.04



## Working directory inside the container
WORKDIR '/rob_app'



## Environment variables

### General variables
ENV TIMEZONE America/Mexico_City
ENV JUPYTERLAB_VERSION 3.1.0
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8

### Dependencies and packages
ENV DEB_BUILD_DEPS="build-essential \
    python3-dev \
    python3-pip \
    python3-setuptools \
    software-properties-common \
    libgit2-dev \
    dirmngr \
    libgmp3-dev \
    libmpfr-dev"
ENV DEB_PACKAGES="sudo \
    nano \
    vim \
    less \
    git \
    curl \
    wget \
    htop"
ENV PIP_PACKAGES="numpy \
    scipy \
    matplotlib \
    pandas \
    seaborn \
    sympy \
    cvxpy \
    cvxopt \
    pytest"



## Commands execution

### Timezone configuration
RUN apt-get update && echo $TIMEZONE > /etc/timezone && apt-get install -y tzdata

### Installing basic dependencies
RUN apt-get update && apt-get install -y $DEB_BUILD_DEPS $DEB_PACKAGES

### Installing jupyterlab
RUN pip3 install --upgrade pip && pip3 install jupyter jupyterlab==$JUPYTERLAB_VERSION

### Installing pip packages
RUN pip3 install $PIP_PACKAGES



## Default commands
ENTRYPOINT ["/usr/local/bin/jupyter", "lab", "--ip=0.0.0.0", "--no-browser"]
